package TACSCMApp;


/**
* TACSCMApp/SCM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tacscm.idl
* Friday, August 23, 2013 8:55:14 AM CEST
*/

public interface SCM extends SCMOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SCM
