package TACSCMApp;


/**
* TACSCMApp/SCMHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tacscm.idl
* Friday, August 23, 2013 8:55:14 AM CEST
*/

abstract public class SCMHelper
{
  private static String  _id = "IDL:TACSCMApp/SCM:1.0";

  public static void insert (org.omg.CORBA.Any a, TACSCMApp.SCM that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TACSCMApp.SCM extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TACSCMApp.SCMHelper.id (), "SCM");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TACSCMApp.SCM read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SCMStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TACSCMApp.SCM value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TACSCMApp.SCM narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TACSCMApp.SCM)
      return (TACSCMApp.SCM)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TACSCMApp._SCMStub stub = new TACSCMApp._SCMStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TACSCMApp.SCM unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TACSCMApp.SCM)
      return (TACSCMApp.SCM)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TACSCMApp._SCMStub stub = new TACSCMApp._SCMStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
