package TACSCMApp;


/**
* TACSCMApp/SCMOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tacscm.idl
* Friday, August 23, 2013 8:55:14 AM CEST
*/

public interface SCMOperations 
{
  String send (String msg);
  boolean status ();
  short getTime ();
  double getInterestRate ();
  double getLoanInterestRate ();
  double getStorageCost ();
} // interface SCMOperations
